[project]
name = "ecr-updater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.63",
    "kubernetes>=34.1.0",
    "loguru>=0.7.3",
    "python-json-logger>=4.0.0",
]
